// <auto-generated />
namespace TaskMaster.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class QtdTasksPrjeBugsRatioModelProj : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QtdTasksPrjeBugsRatioModelProj));
        
        string IMigrationMetadata.Id
        {
            get { return "202003131806386_QtdTasksPrjeBugsRatioModelProj"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
